### ISSUE TITLE
go2rtc is built in Home Assistant 2024.11

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/Blog#26]
[go2rtc](https://github.com/AlexxIT/go2rtc) is now built into Home Assistant starting from [version 2024.11](https://www.home-assistant.io/blog/2024/11/06/release-202411/). This will allow users to view real time stream from their cameras without any additional configuration, using WebRTC technology.

[![](https://img.youtube.com/vi/_vnrPTdmQys/hqdefault.jpg)](https://www.youtube.com/watch?v=_vnrPTdmQys)

Even though there was no mention of the go2rtc project in the [release notes](https://www.home-assistant.io/blog/2024/11/06/release-202411/), the interest of GitHub users has increased a lot these days. The project has been on GitHub's top [trending page](https://github.com/trending) for a few days. In [Golang trends](https://github.com/trending/go), it was ranked number one 5 days in a row.

<a href="https://trendshift.io/repositories/4628" target="_blank"><img src="https://trendshift.io/api/badge/repositories/4628" alt="AlexxIT%2Fgo2rtc | Trendshift" style="width: 250px; height: 55px;" width="250" height="55"/></a>

All of this got my account into the top 1000 GitHub users (based on stars count) faster than I expected. Thanks to all the users of all my projects for this.

[![AlexxIT](https://github-readme-stats.vercel.app/api?username=alexxit&hide=prs,issues&show_icons=true)](https://github.com/AlexxIT)

## Do I need to remove the go2rtc addon or the custom WebRTC integration?

Probably the most frequent question from people who have been using WebRTC in Home Assistant for a long time. The answer depends on the features you are using.

In the most basic version of viewing the stream from cameras - additional addon or custom integration are no longer needed. But when are they needed?

### Reducing the number of connections to the camera

If you have a good camera, such as a $100 Dahua, it can usually handle multiple connections without any problems.

But if you have a simple, cheap camera, like a $10 TP-Link, it can handle one, maximum two connections. Some models can handle more. If the Wi-Fi connection is not reliable - the second connection may have packet losses. If you have enabled video recording on the card or motion detection on the camera - the load on the camera also increases.

A good solution is to use the go2rtc addon where you set up one connection to that camera. And in all other software where you need a stream - use this single connection.

go2rtc will open the connection when the first client arrives and close the connection when the last client leaves.

### Using advanced sources

go2rtc is not only about RTSP cameras. It supports many formats and some of them exclusively.
For example, HomeKit cameras, Roborok vacuum cleaners, USB cameras, DVRIP protocol, Bubble, Kasa, and [others](https://github.com/AlexxIT/go2rtc#module-streams).

### Using MSE

The [custom card](https://github.com/AlexxIT/go2rtc#go2rtc-home-assistant-integration), in addition to WebRTC technology, also is able to use MSE. 
This technology [supports codecs](https://github.com/AlexxIT/go2rtc#codecs-madness) that WebRTC technology does not yet support. For example, H265 and AAC. 
And this technology also does a better job with external connectivity to your Home Assistant, in case there are any problems connecting via WebRTC. [Nabu Casa](https://www.nabucasa.com/) users should not worry about this problem, because the paid subscription includes access to the [TURN server](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT). One more reason for supporting the Home Assistant core team.

### Using two way audio

The custom card [supports two way audio](https://github.com/AlexxIT/WebRTC#two-way-audio) if the camera supports it.

### Playing TTS on two way cameras

Yes, the custom card [supports this](https://github.com/AlexxIT/WebRTC#stream-to-camera) as well.

### go2rtc in venv installation

go2rtc is only built in Docker versions of Home Assistant (including Supervised and OS). It's not in the regular python version. In this case, you can use go2rtc built into the custom integration. This works even in the windows - [HassWP](https://github.com/AlexxIT/HassWP).

### Conclusion

There are other addon or custom card features that you may be interested in. It is better to explore the documentation.

This was just the first release of Home Assistant with go2rtc built in. There will probably be more and more features in new versions. I know there is work in progress to support two way audio out of the box.

Hopefully, with our combined efforts, Home Assistant users will have the best experience viewing real time video from their cameras.

**Comment by felipecrs** [comment]
@AlexxIT, this is amazing. I have been closely following your hard work at go2rtc and I'm really happy about your achievements. All the best for you!

**Comment by alexanderdominicnesbitt** [comment]
@AlexxIT amazing work, thank you! Do you have any guidance on fixing the dashcast setup now it's natively supported? I loved my camera feed auto casting when detects someone

**Comment by AlexxIT** [comment]
DashCast (casting any webpage) not supported in HA out of box. You can use it only via custom integration - [WebRTC](https://github.com/AlexxIT/WebRTC) or [DashCast](https://github.com/AlexxIT/DashCast).

**Comment by alexanderdominicnesbitt** [comment]
> DashCast (casting any webpage) not supported in HA out of box. You can use it only via custom integration - [WebRTC](https://github.com/AlexxIT/WebRTC) or [DashCast](https://github.com/AlexxIT/DashCast).

Thanks for the reply. Now the Nabu casa (I have a sub) are running the WebRTC server, I assume I point the WebRTC camera config to their servers instead of to the addon config? Anyideas what the Nabu casa server address is?

![image](https://github.com/user-attachments/assets/424296d6-14ab-4681-b18f-1f8faf0fcfd9)

![image](https://github.com/user-attachments/assets/10c8f834-e93b-4f1c-89fd-ece01f76db80)

**Comment by tommyjlong** [comment]
Newbie using only native HA (no custom cards, addOns, Integrations) regarding the 2024.11 feature "WebRTC".
Have a couple of questions for clarity:
1. This [documentation](https://www.home-assistant.io/integrations/rtsp_to_webrtc/#technical-details) uses the terms: "RTSPtoWeb{RTC} server" and "RTSPtoWeb{RTC} proxy server".
a) As for "server", do these two terms mean the same thing?
b) Is go2rtc the implementation of a RTSPtoWeb{RTC} server/proxy-server? Or are they different things?

2. There is a statement in this same document on limitations of [RTSPtoWeb](https://github.com/deepch/RTSPtoWeb) and [RTSPtoWebRTC](https://github.com/deepch/RTSPtoWebRTC). 
a) What is the difference between RTSPtoWeb and RTSPtoWebRTC? 
b) How do they apply to Native HA situation (i.e. no customs)?  
  My confusion is that the limitations referenced in the document point to differing github repositories (from deepch),  yet my thinking is that limitations should apply to the native version of HA's go2rtc which has its own repository (from AlexxIT).

**Comment by felipecrs** [comment]
@tommyjlong, nevermind RTSPToWebRTC. They are separate integrations not related to go2rtc (even though go2rtc can act as a RTSPToWebRTC server). They are also not used by HA unless you explicitly enable them. Personally I believe this integration will be deprecated.

You should refer to:

https://www.home-assistant.io/integrations/go2rtc/

**Comment by Maes152** [comment]
Hi Alexx, thanks for writing this up.
I am a nabu casa subscription user and I've been using your go2rtc addon & "WebRTC Camera" integration for a long time. I also use the custom card. I've never been able to get RTC to work remotely so the custom card switches to MSE when my phone is on 5G. This has been working fine for the most part.

Since you also mentioned that if I keep using my current setup, I can reduce the number of connections to the camera, I think I will keep everything the way it is.

However, my question: Am I somehow able to use Nabu Casa's external RTC turn server _while_ using my current setup? It would be nice to be able to use RTC remotely.

**Comment by AlexxIT** [comment]
1. First you have to make sure that the stream uses the H264 codec. Because H265 will be through MSE anyway.
2. It's reasonable to use TURN from Nabu Casa if you're paying for it anyway. It will only work with a standard lovelace card.
3. You can only use one go2rtc from an addon. And configure HA to use it for the standard card.
4. To guarantee one connection to the camera - you need to configure it in go2rtc, then add it to HA from go2rtc (generic rtsp). Because a standard card will connect both the old and new way to the camera. And this is already two connections at the same time.

**Comment by Maes152** [comment]
Thanks for the quick response, that was helpful.

I've setup HA in configuration.yaml to use the go2rtc addon, but I don't think it's working. When I create a picture-glance card it is seemingly slower than the custom card. It's also running about 7 seconds behind. 
Finally, I don't see an additional stream popup in go2rtc. But to be honest, I have no idea how to confirm that the card is actually using RTC....

This is what I added in the configuration.yaml:
`go2rtc:`
`  url: http://localhost:1984`

Anyway I think I prefer the custom card over the picture-glance card any day of the week. If only because it displays the connection technology on the top right corner.

Will there ever be a change to the custom card so that it is able to use Nabu Casa's turn server?

**Comment by AlexxIT** [comment]
Adding TURN from Nabu Casa to a custom card isn't easy. I don't have time for that yet. And need to ask HA core team for permission to do it.

PS. If the standard card has a white time slider, that's old HLS technology. If the time slider is gray (inactive) - it is WebRTC.

**Comment by meremortals70** [comment]
Apologies Alex, only new and actually had installed gotoRTC brilliant work by the way. After your post here, I am even more confused as you don't seem to make a destination with gotoRTC and webRTC. I know one is the add-on and the second is the integration to HA. Is it a cut down version of gotoRTC and therefore webRTC is no longer needed? What about the custom card?

I have Hikvision for external cameras so from your post I am sure I need the original add-on setup anyway.

**Comment by warez4me** [comment]
After my own not so big experience I have **turned Off** the built-in HA go2rtc excluding it from the default_config.
- HA developers implemented go2rtc configuration in strange way: after each reload the go2rtc's config file is generating automatically under random name. That fact doesn't allow to customize go2rtc's config for permanent using and forces to use another additional instance of go2rtc.
- maybe it's my own wrong suspicions (there's another suspect - ONVIF integration which I have turned Off also), but when I left the go2rtc running alone in separate Docker container - my video streams became a "rock-solid" instead of periodical frequent glitches and interrupts in default environment.  (BTW, questions arose about the work of containerized go2rtc, which prompts me try to run a pure binary).

And I’m not alone, there are many topics on the Internet with similar claims.
But for some reason the problem remains. I understand - "open source" and all that. But then you either don't mention this built-in integration and settings for it, or provide the ability to configure it for permanent use and this will eliminate the need to launch an additional instance of go2rtc with the possibility of mutual conflicts.
Now HA has already reached a state where too many unresolved problems have accumulated, and the developers either do not have time or do not want to solve them, but focus on adding new decorations and minor improvements to the external interface.
I am writing all this to the fact that of course you can be proud (and deservedly so) of the fact that your development has become part of some solid project, but maybe, as an author, it is worthwhile to check a little more deeply how correctly this is done.

**Comment by AlexxIT** [comment]
HA supports connecting to your own go2rtc installation (for advanced users)
https://www.home-assistant.io/integrations/go2rtc/

For basic users, everything is done in such a way that they don't even know what go2rtc is.

go2rtc was not designed to solve all user problems automatically.
If the camera is of high quality from a normal brand, everything will work well out of the box.
If the camera has non-standard behavior, go2rtc can solve this in most cases. But with the user's involvement and with additional settings.

We are communicating with the authors of HA about the function "automatically make the stream normal in any case".
I hope something like this will appear in future versions.

**Comment by warez4me** [comment]
Ok.
Only two questions, just for better understanding.
- For what reason after each reload the HA creates a new automatic copy of config for built-in go2rtc?
- For what purpose and what process automatically inserts new streams into the go2rtc configuration in accordance with the camera entities recently created in HA?

**Comment by felipecrs** [comment]
1. Because they don't need a persistent configuration
2. Through the [go2rtc REST APIs](https://github.com/AlexxIT/go2rtc/tree/master/api)

Note these decisions were taken without @AlexxIT's involvement as far as I understand (please correct if I'm wrong), so maybe this is not the best place to ask about it.

**Comment by AlexxIT** [comment]
1. The current architecture of HA does not allow keeping any process constantly running inside HA. It will be rebooted together with HA. My custom component has been working exactly the same way for several years now - https://github.com/AlexxIT/WebRTC
2. Those who don't like it can use a separate addon. Both my component and the HA core support it. If you are an active camera user, I would recommend this way. If you open cameras a couple of times a week, you can leave it as is.
3. I didn't write the go2rtc integration code. But its logic quite accurately repeats my custom component WebRTC.

**Comment by warez4me** [comment]
Yeah, now I see some misunderstanding from myself.
For a newbie there's too many info. And when You read that "You can install go2rtc in several ways ..." or "It will be automatically installed..." or "It is already built-in.. and You have nothing to do.." ...
I got thinking that I can freely use all possibilities of go2rtc using any of this options.
And most misleading is the name "WebRTC camera" that in its docs is called a "custom component" and appears for user as custom HA card. 
In the same time the go2rtc docs among the other options for install mentions "..the Integration" but not the "component" (who will follow the link at fast look?). Before I have seen that HA itself contains a go2rtc integration. 2+2...
Now I see that HA's built-in go2rtc is don't mention anywhere in docs (and it would be nice to do this) in the meaning of what to do or better what not to do with it.
At the same time now I don't see any point in creating HA camera entities. Perhaps only for ONVIF PTZ use. But HA's ONVIF support for PTZ raises a lot of questions compared to its de-facto standard implementation in the Onvif device manager. Myself I have found another way to produce PTZ actions and deal with other Onvif stuff.
Return to HA's buit-in go2rtc I can say that I don't really know what exactly it can do and how. That's why my choice is to turn it Off.
And it really had a positive effect on the stability of video streams.

**Comment by felipecrs** [comment]
> Now I see that HA's built-in go2rtc is don't mention anywhere in docs (and it would be nice to do this) in the meaning of what to do or better what not to do with it.

I am improving that in https://github.com/AlexxIT/go2rtc/pull/1720 btw.

> Return to HA's buit-in go2rtc I can say that I don't really know what exactly it can do and how.

Its goal is to simply reduce the latency when viewing camera streams from camera entities through the built-in Picture Glance card.

If you add your entity through the built-in ONVIF integration, and your only goal is to be able to stream such entity in your Home Assistant dashboard, and the Picture Glance card is good enough for you, then you may not need to tinker with anything else.

And that's a quick win for starters.

**Comment by warez4me** [comment]
> Its goal is to simply reduce the latency when viewing camera streams from camera entities through the built-in Picture Glance card.
....
> And that's a quick win for starters.

And.. That's all?
Then why should I, as a starter, know about  -
[_**Configuration Variables**_](https://www.home-assistant.io/integrations/go2rtc)
...
_**debug_ui** boolean (Optional, default: false)
Enables the UI of the go2rtc, which helps debugging WebRTC issues. The debug_ui should only be enabled during debugging as it will expose port 11984 without any authentication!_
...
Here we got 3 keywords: _**integration, go2rtc**_, which helps _**WebRTC**_
A simple search leads us to a "custom component" (or perhaps it's some kind of advanced custom card),  and its documentation says that it needs go2rtc to work.
But we've already found it!
However, we were not told that any of our changes to its configuration are not saved after the restart.
But they said that _to learn more about go2rtc, refer to the [project’s GitHub page](https://github.com/AlexxIT/go2rtc/)_
I'm studying the go2rtc's documentation, I don't see any special instructions, and then I can count on using the built-in go2rtc for my tasks.
That's what's confusing.

**Comment by felipecrs** [comment]
You shouldn't know any of that. It just works out of the box. You don't even need to know what WebRTC or go2rtc is.

You have found this information because you searched for it. 😅

**Comment by warez4me** [comment]
Yes, and now there is such a situation that the level of my confusion and/or misunderstanding will depend on the order in which I find this information.
The puzzle is gradually taking shape, and I think I understand why new streams are appearing in config for the new camera entities. HA uses them to work with the Picture Glance card.
Ok.
Then why not be more flexible and use go2rtc's ability to work with [multiple configs](https://github.com/AlexxIT/go2rtc/blob/master/internal/app/README.md)?
Define your internal streams in a separate file, and let the user create his own config under a standard or custom name in the common configuration folder and everyone will be happy (seems I was trying to do so in the beginning).
And then no addons will be needed.
Well, what if the user is a kinda advanced and thinks that his external go2rtc is cooler than our built-in one. Ok, we can provide a config with the definition of internal streams as additional for load by the external go2rtc. Definitely it can do this if so was written in its docs. Or it can't?  But there must be an opportunity..
The reason for such reflections is the fact that it is probably better to use a single process instead of several independent and somewhat competing ones that will allocate resources more optimally.
And in the end, I want to see my config the way I created it without the "extra" streams.

**Comment by felipecrs** [comment]
> Then why not be more flexible and use go2rtc's ability to work with [multiple configs](https://github.com/AlexxIT/go2rtc/blob/master/internal/app/README.md)?

That's an advanced use case in Nabu Casa's perspective, and that's exactly why the official integration allows you to supply your own go2rtc url.

> The reason for such reflections is the fact that it is probably better to use a single process instead of several independent and somewhat competing ones that will allocate resources more optimally.

When you set the go2rtc url in the official go2rtc integration, the official integration will not start any go2rtc process.

**Comment by warez4me** [comment]
That's what I'm talking about.
Just need to write these couple dozen words from your several recent comments in addition to [what already is](https://www.home-assistant.io/integrations/go2rtc).
And then me or people like me wouldn't have to waste own time on stupid experiments and Google and then not write hundreds of words here.

**Comment by felipecrs** [comment]
Right. By the way all these documents are open source, and contributions to improve them are generally welcome.

**Comment by warez4me** [comment]
As I see, You have know so much about this.
My IP video experience is about 3 months and I have more questions then answers.
I don't think I'm the more suitable contributor of the two of us.
How about the copy-paste right now ;)
No offense.

**Comment by felipecrs** [comment]
Yeah, don't worry, I know the feeling. Even I am not very comfortable to contribute to these docs.

**Comment by warez4me** [comment]
Yeah, it's left to hope that the top guys will someday find it necessary to supplement the docs.

**Comment by Liquidmasl** [comment]
I am at a loss getting a single usb camera to work..
I sit now for 2 days and just dont understand it. 

```
streams:
  newusb: v4l2:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080&framerate=15

```

This was the content of my go2rts.yaml file. But I dont know where to put it now. 
Nothing in the new go2rts component agrees with it, and the documentation is non existent. 
No LLM out there no matter how premium and how long thinking can provide me a solution that works. 

I come here with tears in my eyes in the hopes of some help... help?

Do I need to provide a url to... what? why?
Why cant I set my own stream like it was?

And I also tried using just the addon, ignoring the built in solution. but then the entity viewer just doesnt work, as it tries to connect to the 1 prefixed port for something, even though i never mention it. 

I am at a loss here


Edit: Well after 2 days it randomly started working with the go2rtc addon... I dont know what changed... I havent even restarted ha or reloaded anything...
But after reding through this here, its just 1 single camera I will look at every few weeks. Having the service only run when its actually needed and not all the time does make sense. So using the built in version might be beneficial still.. so If someone can help me getting it to work wthout the addon I would be happz about that. looks like the addin does need quite some cpu


Edit Edit:
I sweat it know when I wronte something into github...
Now the error is back

`Failed to start WebRTC stream: webrtc: streams: exec/rtsp [rtsp @ 0x7faae0aa0000] method DESCRIBE failed: 404 Not Found [in#0 @ 0x7faae0c12b00] Error opening input: Server returned 404 Not Found Error opening input file rtsp://127.0.0.1:18554/camera.usb_what?audio&source=ffmpeg:camera.usb_what%23audio%3Dopus%23query%3Dlog_level%3Ddebug&log_level=debug. Error opening input files: Server returned 404 Not Found
`

So somethgin is trying to access the 1 prefixed port again from the ha core go2rtc.. I dont know..
Also the stream has like a delay of 2-3 minutes.. hm

**Comment by felipecrs** [comment]
The go2rtc documentation in Home Assistant could indeed be clearer that it does not accept a configuration file.

**Comment by Liquidmasl** [comment]
> The go2rtc documentation in Home Assistant could indeed be clearer that it does not accept a configuration file.

Yeah and it could explain how to get custom streams working still..

**Comment by felipecrs** [comment]
I think that's beyond the integration s purpose.

But at least you can run your own go2rtc instance and supply its URL to the integration.

And then you can setup custom streams as you wish.

**Comment by Liquidmasl** [comment]
> I think that's beyond the integration s purpose.
> 
> But at least you can run your own go2rtc instance and supply its URL to the integration.
> 
> And then you can setup custom streams as you wish.

I tried that as well, no dice. Getting connection refused errors. 

Also it starts creating streams in the go2rtc.yaml file that have random configurations. 
So the built in go2rtc still does stuff that is not documented and are unexprected.

I just added usbstream. the rest just appeared


```
# go2rtc.yaml
streams:
  usbstream: v4l2:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080&framerate=15
  camera.usb_alt:
    - rtsp://127.0.0.1:8554/usbstream
    - ffmpeg:camera.usb_alt#audio=opus#query=log_level=debug
  camera.usb:
    - rtsp://127.0.0.1:18554/usbstream
    - ffmpeg:camera.usb#audio=opus#query=log_level=debug
```

```
#configuration.yaml
default_config:

go2rtc:
  url: http://127.0.0.1:1984

camera:
  - platform: ffmpeg
    name: USB
    input: >-
      -rtsp_transport tcp rtsp://127.0.0.1:18554/usbstream
  - platform: ffmpeg
    name: USB_alt
    input: >-
      -rtsp_transport tcp rtsp://127.0.0.1:8554/usbstream
```


Errors:
```
Logger: homeassistant.components.stream.stream.camera.usb_alt
Source: components/stream/__init__.py:491
integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 4:19:55 PM (1 occurrence)
Last logged: 4:19:55 PM

Error from stream worker: Not Found error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found, rtsp://127.0.0.1:8554/usbstream)
```

```
Logger: homeassistant.components.stream.stream.camera.usb
Source: components/stream/__init__.py:491
integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 4:19:51 PM (1 occurrence)
Last logged: 4:19:51 PM

Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused, rtsp://127.0.0.1:18554/usbstream)
```

I am at a loss here. Could not have believed that it is such an issue getting a usb cam to work ):



Also tried...

```
#configuration.yaml
go2rtc:
  url: http://127.0.0.1:1984

camera:
  - platform: ffmpeg
    name: USB
    input: >-
      -rtsp_transport tcp rtsp://127.0.0.1:8554/camera.usb (also with 18554)


#go2rtc.yaml
streams:
  camera.usb:
    - v4l2:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080&framerate=15
```

Also not working. connection refuesed...
Also the go2rtc stream is just overwritten on restart. 
so with the config you see here after restart its just 

```
streams:
  camera.usb:
    - rtsp://127.0.0.1:8554/camera.usb
    - ffmpeg:camera.usb#audio=opus#query=log_level=debug
```

I am losing it

# I tried more! 

what the heck, mayne it needs to go into circles.. lets try..

```
#configuration.yaml
go2rtc:
  url: http://127.0.0.1:1984

camera:
  - platform: ffmpeg
    name: USB
    input: >-
      -rtsp_transport tcp rtsp://127.0.0.1:8554/usb


#go2rtc.yaml
streams:
  usb:
    - v4l2:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080&framerate=15

  camera.usb:
    - rtsp://127.0.0.1:8554/usb
    - ffmpeg:camera.usb#audio=opus#query=log_level=debug
```

In the go2rtc frontend, both streams work, funny enough. but in home assistant it does not work. 

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:237
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:05:48 PM (2 occurrences)
Last logged: 5:06:14 PM

[140623683271584] Error handling message: Unknown error (unknown_error) Marcel from 62.178.198.156 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 237, in async_handle
    handler(self.hass, self, schema(msg))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 236, in handle_unsubscribe_events
    connection.subscriptions.pop(subscription)()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 765, in close_webrtc_session
    self._webrtc_provider.async_close_session(session_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/go2rtc/__init__.py", line 291, in async_close_session
    ws_client = self._sessions.pop(session_id)
KeyError: '01K7YG2FQBXNFF9VM48HDD5GPW'
```

WHAT IS GOING ON

## hey theres more!

So I have a functioning h265 stream now

```
streams:
  usb:
    - exec:ffmpeg -f v4l2 -input_format mjpeg -framerate 15 -video_size 1280x720 -i /dev/video0 -vf format=yuv420p -c:v libx264 -preset ultrafast -tune zerolatency -profile:v baseline -level 3.1 -pix_fmt yuv420p -b:v 1200k -g 30 -bf 0 -an -f rtsp {output}

````

I was hoping homeassistant would autoamtically pick it up and add it as entity or something, but this does not happen. 

I can add a camera to the configuration.yaml, but this again automatically creates a new stream, that just forces me into using a transcode step which explodes latency, i cant change those settings cause they are overwritten whenever i try to look at the entity. 
It is ** SO FRUSTRATING**. The stream works fine everywhere, but i cant get it into home assistant. 
this is a 2 day endevour now for a god damn usb camera. 

# HELP

**Comment by warez4me** [comment]
@Liquidmasl
Forget about using HA built-in go2rtc if You want to configure own go2rtc streams.. Read my comments above.

```
#configuration.yaml
go2rtc:
  url: http://127.0.0.1:1984

camera:
  - platform: ffmpeg
    name: USB
    input: >-
      -rtsp_transport tcp rtsp://127.0.0.1:8554/usb
```

All ports of the HA built-in go2rtc are changed by adding 10000, so 1984 and 8554 are illegal values and may be the reason for your "Error not found..." log message.

For own usage You need to run separate go2rtc instance.

If You already run it - don't look on auto-added streams, just forget about it.
Use only own streams.
Myself I refused to use HA camera entities. Using only go2rtc streams and "Frigate" adv card.

**Comment by felipecrs** [comment]
> Myself I refused to use HA camera entities. Using only go2rtc streams and "Frigate" adv card.

Yeah, I recommend that too. WebRTC Camera or Advanced Camera Card.

**Comment by Liquidmasl** [comment]
No yeah I have come that far it just didnt work as well.

the ffmpeg camera will somehow still add a new stram to the go2rtc yaml from the addon, and will only use that. ignoring my settings. so the stream never shows up. OR it is badly transcoded and has minutes delay. 
So It never uses my own stream. It ignores it just as much as I ignore the automatically created once.

WebRTC Camera works great btw, but I really wanted the entity for all the other homeassistant media shenanigans, like throwing the cam directly to my google tv or something.

# But I succeeded in the end
I managed to do it, not with ffmpeg camera, but a generic camera that i connected to my stream via the UI. 

But that wasn't joyful either, cause the UI shows you a preview, if that preview works the user should click on a 'everything looks fine' checkmark and submit. **But this review never worked once.** 
I just gave up and went to sleep, clicked the checkmark and submit, even though the preview didnt work. I was fed up with it.
And guess what? **now the entity works fine.** 

So after 2 days trying all combinations of everything i just got bamboozled by shitty UI (generic camera refuses to be configured through yaml).

The whole experience was quite horrible ngl

**Comment by warez4me** [comment]
As I remember now, the troubles with generic camera creation was arising for cams which are don't have the native snapshot stream support (now I think so), but in such cases I simply did a submit (same as You did). And then such cams almost always show empty preview but were more-less workable.
As for streaming to google tv - look [this](https://seanblanchfield.com/2023/06/realtime-pip-cameras-on-tv-with-home-assistant-v2),[this](https://github.com/AlexxIT/WebRTC/issues/34), [this](https://www.home-assistant.io/integrations/rest_command), [this](https://github.com/rogro82/PiPup) - perhaps it'll be useful for You.
